name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  saucedemo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: saucedemo
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: saucedemo
      - name: Run tests
        run: npx playwright test
        working-directory: saucedemo
      - uses: actions/upload-artifact@v5
        if: always()
        with:
          name: playwright-report
          path: saucedemo/playwright-report/
  restful-booker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: saucedemo
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: restful-booker
      - name: Run tests
        run: npx playwright test
        working-directory: saucedemo
      - uses: actions/upload-artifact@v5
        if: always()
        with:
          name: playwright-report
          path: saucedemo/playwright-report/